function(shader_bytecode_glsl_macro_name SHADER_FILE OUT_HEADER_NAME OUT_GLOBAL_VAR)
    get_filename_component(_shader_name "${SHADER_FILE}" NAME)
    string(REPLACE "." "_" _header_name "${_shader_name}")
    string(TOUPPER "${_header_name}" _global_var)
    set(${OUT_HEADER_NAME} "${_header_name}" PARENT_SCOPE)
    set(${OUT_GLOBAL_VAR} "${_global_var}" PARENT_SCOPE)
endfunction()

function(shader_bytecode_hlsl_macro_name SHADER_FILE OUT_HEADER_NAME OUT_GLOBAL_VAR)
    get_filename_component(_shader_name "${SHADER_FILE}" NAME)
    string(REGEX REPLACE "\\.hlsl$" "" _shader_base_name "${_shader_name}")
    string(REPLACE "." "_" _header_name "${_shader_base_name}")
    string(TOUPPER "${_header_name}" _global_var)
    set(${OUT_HEADER_NAME} "${_header_name}" PARENT_SCOPE)
    set(${OUT_GLOBAL_VAR} "${_global_var}" PARENT_SCOPE)
endfunction()

function(generate_render_shader_bytecode_header)
    set(_options "")
    set(_one_value_args OUTPUT_HEADER)
    set(_multi_value_args GLSL_SHADERS HLSL_SHADERS HLSL_RT_SHADERS)
    cmake_parse_arguments(ARG "${_options}" "${_one_value_args}" "${_multi_value_args}" ${ARGN})

    if(NOT ARG_OUTPUT_HEADER)
        message(FATAL_ERROR "generate_render_shader_bytecode_header requires OUTPUT_HEADER")
    endif()

    set(_content "/**\n * @file render_shader_bytecode_gen.h\n * @brief Auto-generated shader bytecode glue macros. Do not edit.\n */\n#pragma once\n\n")

    # --- Vulkan (GLSL SPIR-V) ---
    string(APPEND _content "#if PICCOLO_ENABLE_VULKAN_BACKEND && defined(__has_include)\n")

    set(_vulkan_macro_names "")
    foreach(_shader IN LISTS ARG_GLSL_SHADERS)
        shader_bytecode_glsl_macro_name("${_shader}" _header_name _global_var)
        list(APPEND _vulkan_macro_names "${_global_var}")
        string(APPEND _content "#if __has_include(<${_header_name}.h>)\n")
        string(APPEND _content "#include <${_header_name}.h>\n")
        string(APPEND _content "#define PICCOLO_VULKAN_${_global_var} ${_global_var}\n")
        string(APPEND _content "#else\n")
        string(APPEND _content "#define PICCOLO_VULKAN_${_global_var} ::Piccolo::emptyVulkanShaderBytecode()\n")
        string(APPEND _content "#endif\n")
    endforeach()

    # gpu_skinning has no GLSL source; keep the macro for symmetry with hand-written header.
    if(NOT "GPU_SKINNING_COMP" IN_LIST _vulkan_macro_names)
        list(APPEND _vulkan_macro_names "GPU_SKINNING_COMP")
        string(APPEND _content "#if __has_include(<gpu_skinning_comp.h>)\n")
        string(APPEND _content "#include <gpu_skinning_comp.h>\n")
        string(APPEND _content "#define PICCOLO_VULKAN_GPU_SKINNING_COMP GPU_SKINNING_COMP\n")
        string(APPEND _content "#else\n")
        string(APPEND _content "#define PICCOLO_VULKAN_GPU_SKINNING_COMP ::Piccolo::emptyVulkanShaderBytecode()\n")
        string(APPEND _content "#endif\n")
    endif()

    string(APPEND _content "#else\n")
    foreach(_macro_name IN LISTS _vulkan_macro_names)
        string(APPEND _content "#define PICCOLO_VULKAN_${_macro_name} ::Piccolo::emptyVulkanShaderBytecode()\n")
    endforeach()
    string(APPEND _content "#endif\n\n")

    # --- D3D12 (DXIL) ---
    string(APPEND _content "#if PICCOLO_ENABLE_D3D12_BACKEND && PICCOLO_D3D12_SHADER_BYTECODE_AVAILABLE != 0 && defined(__has_include)\n")

    set(_d3d12_macro_names "")
    foreach(_shader IN LISTS ARG_HLSL_SHADERS)
        shader_bytecode_hlsl_macro_name("${_shader}" _header_name _global_var)
        list(APPEND _d3d12_macro_names "${_global_var}")
        string(APPEND _content "#if __has_include(<dxil_cpp/${_header_name}.h>)\n")
        string(APPEND _content "#include <dxil_cpp/${_header_name}.h>\n")
        string(APPEND _content "#define PICCOLO_D3D12_${_global_var} D3D12_${_global_var}\n")
        string(APPEND _content "#else\n")
        string(APPEND _content "#define PICCOLO_D3D12_${_global_var} ::Piccolo::emptyD3D12ShaderBytecode()\n")
        string(APPEND _content "#endif\n")
    endforeach()

    string(APPEND _content "#else\n")
    foreach(_macro_name IN LISTS _d3d12_macro_names)
        string(APPEND _content "#define PICCOLO_D3D12_${_macro_name} ::Piccolo::emptyD3D12ShaderBytecode()\n")
    endforeach()
    string(APPEND _content "#endif\n\n")

    # --- Vulkan ray tracing (HLSL -> SPIR-V via dxc) ---
    string(APPEND _content "// Vulkan ray tracing library (SPIR-V compiled from shared HLSL via dxc).\n")
    string(APPEND _content "#if PICCOLO_ENABLE_VULKAN_BACKEND && defined(__has_include) && __has_include(<vulkan_cpp/path_tracing_lib.h>)\n")
    string(APPEND _content "#include <vulkan_cpp/path_tracing_lib.h>\n")
    string(APPEND _content "#define PICCOLO_VULKAN_PATH_TRACING_LIB VULKAN_PATH_TRACING_LIB\n")
    string(APPEND _content "#else\n")
    string(APPEND _content "#define PICCOLO_VULKAN_PATH_TRACING_LIB ::Piccolo::emptyVulkanShaderBytecode()\n")
    string(APPEND _content "#endif\n\n")

    string(APPEND _content "#if PICCOLO_ENABLE_VULKAN_BACKEND && defined(__has_include) && __has_include(<vulkan_cpp/gpu_skinning_comp.h>)\n")
    string(APPEND _content "#include <vulkan_cpp/gpu_skinning_comp.h>\n")
    string(APPEND _content "#undef PICCOLO_VULKAN_GPU_SKINNING_COMP\n")
    string(APPEND _content "#define PICCOLO_VULKAN_GPU_SKINNING_COMP VULKAN_GPU_SKINNING_COMP\n")
    string(APPEND _content "#endif\n")

    get_filename_component(_output_dir "${ARG_OUTPUT_HEADER}" DIRECTORY)
    if(_output_dir AND NOT EXISTS "${_output_dir}")
        file(MAKE_DIRECTORY "${_output_dir}")
    endif()
    file(WRITE "${ARG_OUTPUT_HEADER}" "${_content}")
endfunction()
