name: Build Linux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [debug, release]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Install dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y \
              libxrandr-dev \
              libxrender-dev \
              libxinerama-dev \
              libxcursor-dev \
              libxi-dev \
              libglvnd-dev \
              libvulkan-dev \
              clang \
              libc++-dev
        
      - name: Build
        run: ./build_linux.sh ${{matrix.configuration}}
